import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../controllers/finance_controller.dart';
import '../models/goal_model.dart';
import '../theme/app_theme.dart';

class AddGoalScreen extends StatefulWidget {
  const AddGoalScreen({super.key});

  @override
  State<AddGoalScreen> createState() => _AddGoalScreenState();
}

class _AddGoalScreenState extends State<AddGoalScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _targetController = TextEditingController();
  final _currentController = TextEditingController(text: '0');
  
  DateTime _deadline = DateTime.now().add(const Duration(days: 90));
  String _selectedIcon = 'Shield';

  final List<Map<String, dynamic>> _availableIcons = [
    {'name': 'Shield', 'icon': LucideIcons.shield},
    {'name': 'Plane', 'icon': LucideIcons.plane},
    {'name': 'Laptop', 'icon': LucideIcons.laptop},
    {'name': 'Car', 'icon': LucideIcons.car},
    {'name': 'Home', 'icon': LucideIcons.home},
    {'name': 'Shopping', 'icon': LucideIcons.shoppingBag},
    {'name': 'Gift', 'icon': LucideIcons.gift},
    {'name': 'Trending', 'icon': LucideIcons.trendingUp},
  ];

  @override
  void dispose() {
    _titleController.dispose();
    _targetController.dispose();
    _currentController.dispose();
    super.dispose();
  }

  void _selectDeadline() async {
    final pickedDate = await showDatePicker(
      context: context,
      initialDate: _deadline,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365 * 10)),
    );

    if (pickedDate != null) {
      setState(() {
        _deadline = pickedDate;
      });
    }
  }

  void _saveGoal() {
    if (_formKey.currentState!.validate()) {
      final target = double.tryParse(_targetController.text) ?? 0.0;
      final current = double.tryParse(_currentController.text) ?? 0.0;

      if (target <= 0) {
        Get.snackbar('Error', 'Target amount must be greater than 0');
        return;
      }

      final goal = GoalModel(
        id: '', // Generated by Firestore
        title: _titleController.text.trim(),
        targetAmount: target,
        currentAmount: current,
        deadline: _deadline,
        icon: _selectedIcon,
      );

      Get.find<FinanceController>().addGoal(goal);
      Get.back();
      
      Get.snackbar(
        'Success',
        'Goal created successfully!',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.green.withOpacity(0.1),
        colorText: Colors.green[800],
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final dateString = DateFormat('dd MMM yyyy').format(_deadline);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Savings Goal'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppTheme.spacingMd),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Title Field
              TextFormField(
                controller: _titleController,
                textCapitalization: TextCapitalization.sentences,
                decoration: const InputDecoration(
                  labelText: 'Goal Title',
                  prefixIcon: Icon(LucideIcons.target, size: 20),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a goal title';
                  }
                  return null;
                },
              ),
              const SizedBox(height: AppTheme.spacingMd),

              // Target Amount
              TextFormField(
                controller: _targetController,
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(
                  labelText: 'Target Amount',
                  prefixIcon: Icon(LucideIcons.indianRupee, size: 20),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a target amount';
                  }
                  if (double.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              const SizedBox(height: AppTheme.spacingMd),

              // Initial Amount
              TextFormField(
                controller: _currentController,
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(
                  labelText: 'Already Saved (Optional)',
                  prefixIcon: Icon(LucideIcons.piggyBank, size: 20),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) return null;
                  if (double.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              const SizedBox(height: AppTheme.spacingLg),

              // Select Icon Category
              Text(
                'Select Goal Icon',
                style: theme.textTheme.titleMedium,
              ),
              const SizedBox(height: AppTheme.spacingSm),
              GridView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 4,
                  crossAxisSpacing: AppTheme.spacingSm,
                  mainAxisSpacing: AppTheme.spacingSm,
                  childAspectRatio: 1.2,
                ),
                itemCount: _availableIcons.length,
                itemBuilder: (context, index) {
                  final item = _availableIcons[index];
                  final isSelected = _selectedIcon == item['name'];
                  
                  return InkWell(
                    onTap: () {
                      setState(() {
                        _selectedIcon = item['name'];
                      });
                    },
                    borderRadius: BorderRadius.circular(AppTheme.radiusMd),
                    child: Container(
                      decoration: BoxDecoration(
                        border: Border.all(
                          color: isSelected
                              ? theme.colorScheme.primary
                              : theme.colorScheme.outline.withOpacity(0.2),
                          width: isSelected ? 2 : 1,
                        ),
                        borderRadius: BorderRadius.circular(AppTheme.radiusMd),
                        color: isSelected
                            ? theme.colorScheme.primary.withOpacity(0.1)
                            : Colors.transparent,
                      ),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(
                            item['icon'] as IconData,
                            color: isSelected
                                ? theme.colorScheme.primary
                                : theme.colorScheme.onSurface.withOpacity(0.6),
                            size: 24,
                          ),
                          const SizedBox(height: 4),
                          Text(
                            item['name'] as String,
                            style: theme.textTheme.bodySmall?.copyWith(
                              fontSize: 10,
                              fontWeight: isSelected ? FontWeight.bold : null,
                              color: isSelected ? theme.colorScheme.primary : null,
                            ),
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
              const SizedBox(height: AppTheme.spacingLg),

              // Deadline picker
              Card(
                child: ListTile(
                  leading: const Icon(LucideIcons.calendar),
                  title: const Text('Deadline Date'),
                  subtitle: Text(dateString),
                  trailing: const Icon(LucideIcons.chevronRight),
                  onTap: _selectDeadline,
                ),
              ),
              const SizedBox(height: AppTheme.spacingXl),

              // Submit Button
              ElevatedButton(
                onPressed: _saveGoal,
                style: ElevatedButton.styleFrom(
                  backgroundColor: theme.colorScheme.primary,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: AppTheme.spacingMd),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(AppTheme.radiusLg),
                  ),
                  elevation: 0,
                ),
                child: Text(
                  'Create Goal',
                  style: theme.textTheme.titleMedium?.copyWith(
                    color: Colors.white,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
